import type { MessageAngle, MessageLanguage, MessageTone } from "@/lib/types";

export const APP_NAME = "J-Digital AI Lead Assistant (JALA)";

export const DEFAULT_CATEGORY_SEEDS: Array<{
  name: string;
  defaultAngle: MessageAngle;
  keywords: string[];
}> = [
  {
    name: "Auto Service",
    defaultAngle: "organization",
    keywords: [
      "auto repair",
      "car service center",
      "mechanic shop",
      "wheel alignment",
      "change oil",
      "battery replacement",
      "auto electrical",
      "car maintenance",
    ],
  },
  {
    name: "Car Rental",
    defaultAngle: "booking",
    keywords: [
      "car rental",
      "rent a car",
      "self drive rental",
      "chauffeur service",
      "airport transfer",
      "vehicle rental",
      "daily car rental",
      "van rental",
    ],
  },
  {
    name: "Construction",
    defaultAngle: "organization",
    keywords: [
      "construction company",
      "general contractor",
      "design and build",
      "renovation contractor",
      "home builder",
      "fit out contractor",
      "civil works",
      "roofing contractor",
    ],
  },
  {
    name: "Dental Clinic",
    defaultAngle: "booking",
    keywords: [
      "dental clinic",
      "dentist",
      "cosmetic dentist",
      "family dentist",
      "teeth whitening",
      "dental implants",
      "orthodontist",
      "braces clinic",
    ],
  },
  {
    name: "Fast Food",
    defaultAngle: "low_volume",
    keywords: [
      "fast food",
      "takeout restaurant",
      "burger shop",
      "fried chicken",
      "food delivery",
      "quick service restaurant",
      "drive thru",
      "meal deals",
    ],
  },
  {
    name: "Furniture",
    defaultAngle: "low_volume",
    keywords: [
      "furniture store",
      "home furniture",
      "office furniture",
      "custom furniture",
      "sofa store",
      "bed frame store",
      "dining set",
      "furniture showroom",
    ],
  },
  {
    name: "Gym Fitness",
    defaultAngle: "booking",
    keywords: [
      "gym",
      "fitness center",
      "fitness studio",
      "personal trainer",
      "crossfit gym",
      "pilates studio",
      "weight loss center",
      "membership gym",
    ],
  },
  {
    name: "Hotel",
    defaultAngle: "booking",
    keywords: [
      "hotel",
      "business hotel",
      "boutique hotel",
      "inn",
      "room booking",
      "accommodation",
      "hotel reservation",
      "suite hotel",
    ],
  },
  {
    name: "Medical Clinics",
    defaultAngle: "booking",
    keywords: [
      "medical clinic",
      "health clinic",
      "doctor consultation",
      "family medicine clinic",
      "diagnostic clinic",
      "laboratory clinic",
      "outpatient clinic",
      "primary care clinic",
    ],
  },
  {
    name: "Real State",
    defaultAngle: "organization",
    keywords: [
      "real estate agency",
      "realty",
      "property broker",
      "property management",
      "house and lot for sale",
      "condo for sale",
      "property listing",
      "real estate broker",
    ],
  },
  {
    name: "Rental Services",
    defaultAngle: "organization",
    keywords: [
      "rental services",
      "equipment rental",
      "event rental",
      "party rental",
      "machine rental",
      "tool rental",
      "for rent service",
      "leasing service",
    ],
  },
  {
    name: "Resort",
    defaultAngle: "booking",
    keywords: [
      "resort",
      "private resort",
      "beach resort",
      "villa resort",
      "overnight stay",
      "resort booking",
      "swimming resort",
      "holiday resort",
    ],
  },
  {
    name: "Restaurant",
    defaultAngle: "low_volume",
    keywords: [
      "restaurant",
      "family restaurant",
      "cafe restaurant",
      "dine in",
      "food delivery",
      "table reservation",
      "eatery",
      "casual dining",
    ],
  },
  {
    name: "Salon",
    defaultAngle: "booking",
    keywords: [
      "beauty salon",
      "hair salon",
      "hair color salon",
      "keratin treatment",
      "nail salon",
      "blow dry bar",
      "eyelash salon",
      "makeup studio",
    ],
  },
  {
    name: "Spa",
    defaultAngle: "booking",
    keywords: [
      "spa",
      "massage spa",
      "wellness spa",
      "facial spa",
      "body scrub spa",
      "relaxation spa",
      "therapeutic massage",
      "day spa",
    ],
  },
  {
    name: "Aesthetic Clinic",
    defaultAngle: "booking",
    keywords: [
      "aesthetic clinic",
      "skin clinic",
      "derma clinic",
      "laser treatment clinic",
      "botox clinic",
      "facial treatment clinic",
      "skin rejuvenation",
      "beauty clinic",
    ],
  },
  {
    name: "Veterinary Clinic",
    defaultAngle: "booking",
    keywords: [
      "veterinary clinic",
      "vet clinic",
      "animal hospital",
      "pet vaccination",
      "pet checkup",
      "pet wellness",
      "pet grooming clinic",
      "veterinarian",
    ],
  },
  {
    name: "Law Firm",
    defaultAngle: "organization",
    keywords: [
      "law firm",
      "legal services",
      "attorney office",
      "corporate lawyer",
      "litigation lawyer",
      "notary public",
      "legal consultation",
      "legal office",
    ],
  },
  {
    name: "Accounting & Tax Services",
    defaultAngle: "organization",
    keywords: [
      "accounting services",
      "bookkeeping services",
      "tax filing",
      "payroll services",
      "cpa firm",
      "auditing services",
      "business registration",
      "financial reporting",
    ],
  },
  {
    name: "Insurance Agency",
    defaultAngle: "low_volume",
    keywords: [
      "insurance agency",
      "life insurance",
      "health insurance",
      "car insurance",
      "insurance broker",
      "insurance advisor",
      "policy renewal",
      "insurance quote",
    ],
  },
  {
    name: "Home Services",
    defaultAngle: "organization",
    keywords: [
      "plumbing services",
      "electrical services",
      "aircon repair",
      "cleaning services",
      "pest control",
      "handyman services",
      "home maintenance",
      "appliance repair",
    ],
  },
  {
    name: "Travel Agency",
    defaultAngle: "booking",
    keywords: [
      "travel agency",
      "travel and tours",
      "tour package",
      "flight booking",
      "holiday package",
      "ticketing office",
      "visa assistance",
      "travel services",
    ],
  },
  {
    name: "Event Services",
    defaultAngle: "organization",
    keywords: [
      "event planner",
      "wedding coordinator",
      "event management",
      "catering services",
      "event styling",
      "photo and video",
      "party organizer",
      "corporate events",
    ],
  },
];

export const QUICK_START_CATEGORY_NAMES = [
  "Dental Clinic",
  "Construction",
  "Aesthetic Clinic",
  "Home Services",
  "Rental Services",
] as const;

export const DEFAULT_LOCATIONS = [
  {
    name: "Tacloban City",
    city: "Tacloban City",
    region: "Region 8",
    country: "Philippines",
  },
  {
    name: "Region 8",
    city: null,
    region: "Region 8",
    country: "Philippines",
  },
];

export const DEFAULT_LANGUAGES: MessageLanguage[] = ["Taglish", "English", "Tagalog", "Waray"];
export const DEFAULT_TONES: MessageTone[] = ["Soft", "Direct", "Value-Focused"];
